<?php require('template/header.phtml') ?>

<h2>Edit Placement</h2>

<div class="container">
    <div class="row">
        <div class="col d-flex justify-content-center">
            <form method="post" class="form text-primary">
                <div class="form-group">
                    <label for="placementSelected">Select a placement: </label>
                    <select class="form-control" name="placementSelected">
                        <option value="noPlacement">No Placement Selected</option>
                        <?php
                        foreach ($view->placementDataSet as $placement)
                        {
                            echo '<option value="' . $placement->getPlacementID() . '">' . $placement->getDescription() . '</option>';
                        }
                        ?>
                    </select>
                </div>
                <input type="submit" class="btn btn-secondary" name="placementSelectButton" value="Select Placement">
            </form>
        </div>
    </div>
</div>

<?php
if (isset($_SESSION["placementSelect"])) {
    $placement = $view->emptyPlacementDataSet->fetchSpecificPlacement($_SESSION["placementSelect"]);
?>
    <form method="post" action="" class="form text-primary" enctype="multipart/form-data">
        <div class="form-group">
            <label for="placementDescripton">Description *</label>
            <textarea class="form-control" placeholder="Description" rows = "5" cols = "50" name="placementDescripton" required><?php echo $placement->getDescription(); ?></textarea>
        </div>
        <div class="form-group">
            <label for="placementSkillsRequired">Skills Required *</label>
            <input type="text" class="form-control" placeholder="Skills Required" name="placementSkillsRequired" value="<?php echo $placement->getSkillsRequired(); ?>" required>
        </div>
        <div class="form-group">
            <label for="placementSalary">Salary *</label>
            <input type="text" class="form-control" placeholder="Salary" name="placementSalary" value="<?php echo $placement->getSalary(); ?>" required>
        </div>
        <div class="form-group">
            <label for="placementLocation">Location *</label>
            <input type="text" class="form-control" placeholder="Location" name="placementLocation" value="<?php echo $placement->getLocation(); ?>" required>
        </div>
        <div class="form-group">
            <label for="placementStart placementEnd">Start and End Date *</label>
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <input type="date" class="form-control" name="placementStart" value="<?php echo $placement->getStart(); ?>" required>
                    </div>
                    <div class="col-sm d-flex justify-content-center">
                        -
                    </div>
                    <div class="col-sm">
                        <input type="date" class="form-control" name="placementEnd" value="<?php echo $placement->getEnd() ?>" required>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="placementType">Type *</label>
            <select class="form-control" name="placementType">
                <option value="agriculture" <?php if ($placement->getType() == "agriculture")echo "selected"; ?>> Agriculture, Food, and Natural Resources</option>
                <option value="architecture" <?php if ($placement->getType() == "architecture")echo "selected"; ?>>Architecture and Construction</option>
                <option value="arts" <?php if ($placement->getType() == "arts")echo "selected"; ?>>Arts, Audio/Video Technology, and Communication</option>
                <option value="business" <?php if ($placement->getType() == "business")echo "selected"; ?>>Business and Finance</option>
                <option value="education" <?php if ($placement->getType() == "education")echo "selected"; ?>>Education and Training</option>
                <option value="government" <?php if ($placement->getType() == "government")echo "selected"; ?>>Government and Public Administration</option>
                <option value="health" <?php if ($placement->getType() == "health")echo "selected"; ?>>Health Science</option>
                <option value="it" <?php if ($placement->getType() == "it")echo "selected"; ?>>Information Technology</option>
                <option value="law" <?php if ($placement->getType() == "law")echo "selected"; ?>>Law, Public Safety, Corrections, and Security</option>
                <option value="marketing" <?php if ($placement->getType() == "marketing")echo "selected"; ?>>Marketing</option>
                <option value="science" <?php if ($placement->getType() == "science")echo "selected"; ?>>Science, Technology, Engineering, and Math</option>
            </select>
        </div>
        <input type="submit" class="btn btn-secondary" name="editPlacementButton" value="Edit Placement">
    </form>
    <?php
    if (isset($_SESSION["placementError"]))
    {
        echo "<p class='error'>" . $_SESSION["placementError"] . "</p>";
        unset($_SESSION["placementError"]);
    }
    ?>

<?php
}
?>


<?php require('template/footer.phtml') ?>
