<?php require("template/header.phtml") ?>

<?php

if (!isset($_SESSION["login"])) {
    echo ' 
            <p class="benefits">
                Placements are work experience that is part of a students degree. It is an excellent opportunity to apply the knowledge
                they have accumulated in their academic years within a working environment. They come with a range of benefits including:
            </p>
            <ul class="benefits">
                <li>Incredibly valuable work experience to add in a student\'s CV</li>
                <li>Greater knowledge of the industry</li>
                <li>A chance to further develop skills</li>
                <li>Provides greater experience in applying for a job</li>
            </ul>
            <form method="post" action="" class="form text-primary">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" placeholder="Email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" placeholder="Password" name="password" required>
                </div>
                <input type="submit" class="btn btn-secondary" name="loginbutton" value="Login">
            </form>';
    if (isset($_SESSION["loginError"]))
    {
        echo "<p class='error'>" . $_SESSION["loginError"] . "</p>";
        unset($_SESSION["loginError"]);
    }
}
else
{
    if($userTableDataSet->checkIfStudent($_SESSION['user_id']))
    {
        ?>
               <h2>Matching Student</h2>

                <div class="container">
                    <?php
                    if (!empty($view->placementDataSet)) {
                    ?>
                    <div class="row">
                        <div class="col-2 d-flex justify-content-center">
                            <form method="post" class="form text-primary">
                                <input id="no" type="submit" class="btn btn-danger" name="studentMatchingNo" value="No">
                            </form>
                         </div>
                        <div id="placement" class="col-8 justify-content-center">
                            <p>Description: <?php echo $view->placementDataSet[0]->getDescription() ?></p>
                            <br>
                            <p>Skills Required: <?php echo $view->placementDataSet[0]->getSkillsRequired() ?></p>
                            <br>
                            <p>Salary: <?php echo $view->placementDataSet[0]->getSalary() ?></p>
                            <br>
                            <p>Location: <?php echo $view->placementDataSet[0]->getLocation() ?></p>
                            <br>
                            <p>Start and End Date: <?php echo $view->placementDataSet[0]->getStart() ?>   |  <?php echo  $view->placementDataSet[0]->getEnd() ?></p>
                            <br>
                            <p>Type: <?php echo $view->placementDataSet[0]->getType() ?> </p>
                            <br>
                            <form method="post" class="form text-primary">
                                <div class="form-group">
                                    <label for="filterType">Filter by Type: </label>
                                    <select class="form-control" name="filterType">
                                        <option value="noFilter">No Filter</option>
                                        <option value="agriculture">Agriculture, Food, and Natural Resources</option>
                                        <option value="architecture">Architecture and Construction</option>
                                        <option value="arts">Arts, Audio/Video Technology, and Communication</option>
                                        <option value="business">Business and Finance</option>
                                        <option value="education">Education and Training</option>
                                        <option value="government">Government and Public Administration</option>
                                        <option value="health">Health Science</option>
                                        <option value="it">Information Technology</option>
                                        <option value="law">Law, Public Safety, Corrections, and Security</option>
                                        <option value="marketing">Marketing</option>
                                        <option value="science">Science, Technology, Engineering, and Math</option>
                                    </select>
                                </div>
                                <div class="col d-flex justify-content-center">
                                    <input type="submit" class="btn btn-secondary" name="filterButton" value="Apply Filter">
                                </div>
                            </form>
                        </div>
                        <div class="col-2 d-flex justify-content-center">
                            <form method="post" class="form text-primary">
                                <input id="yes" type="submit" class="btn btn-success" name="studentMatchingYes" value="Yes">
                            </form>
                        </div>
                    </div>
                    <?php
                    }
                    else
                    {
                    ?>
                    <p>Currently there are no placements available. Please check back again later.</p>
                    <form method="post" class="form text-primary">
                        <div class="form-group">
                            <label for="filterType">Filter by Type: </label>
                            <select class="form-control" name="filterType">
                                <option value="noFilter">No Filter</option>
                                <option value="agriculture">Agriculture, Food, and Natural Resources</option>
                                <option value="architecture">Architecture and Construction</option>
                                <option value="arts">Arts, Audio/Video Technology, and Communication</option>
                                <option value="business">Business and Finance</option>
                                <option value="education">Education and Training</option>
                                <option value="government">Government and Public Administration</option>
                                <option value="health">Health Science</option>
                                <option value="it">Information Technology</option>
                                <option value="law">Law, Public Safety, Corrections, and Security</option>
                                <option value="marketing">Marketing</option>
                                <option value="science">Science, Technology, Engineering, and Math</option>
                            </select>
                        </div>
                        <input type="submit" class="btn btn-secondary" name="filterButton" value="Apply Filter">
                    </form>
                    <?php
                    }
                    ?>
                </div>
        <?php
    }
    else if($userTableDataSet->checkIfEmployer($_SESSION['user_id']))
    {
        ?>
               <h2>Applications</h2>

                <div class="container">
                    <?php
                    if (empty($view->placementDataSet)) {
                        echo '<p>No placements has been created.</p>';
                    } else {
                        foreach ($view->placementDataSet as $placementData) { ?>
                            <div class="row">
                                <div id="application" class="col-8 justify-content-center">
                                    <p>Description: <?php echo $placementData->getDescription() ?></p>
                                    <p>Skills Required: <?php echo $placementData->getSkillsRequired() ?></p>
                                    <p>Salary: <?php echo $placementData->getSalary() ?></p>
                                    <p>Location: <?php echo $placementData->getLocation() ?></p>
                                    <p>Start and End Date: <?php echo $placementData->getStart() ?>  |  <?php echo $placementData->getEnd() ?></p>
                                    <p>Type: <?php echo $placementData->getType() ?> </p>
                                    <table class="table table-hover">
                                        <form method="post" action="" class="form text-primary">
                                        <tbody>
                                            <?php
                                            if (empty($userTableDataSet->studentAppliedPlacements($placementData->getPlacementID()))) {
                                                echo '<p>No student has applied yet.</p>';
                                            } else {
                                                foreach ($userTableDataSet->studentAppliedPlacements($placementData->getPlacementID()) as $appliedStudent) {
                                                    echo '<tr> <td>' . $appliedStudent->getUserID() . '</td> <td>' . '<a href = "CVs/'. $appliedStudent->getUserID() . '_cv.pdf" ><input id="buttons" type="button" class="btn btn-secondary" name="showCV" value="Show Student CV"></a>' . '<input id="buttons" type="hidden" id="hiddenPlacementID" name="hiddenPlacementID" value="'  . $placementData->getPlacementID() . '"><input id="buttons" type="submit" class="btn btn-success" name="employerMatchingYes" value="Accept ' . $appliedStudent->getUserID() . '">' . '<input id="buttons" type="submit" class="btn btn-danger" name="employerMatchingNo" value="Reject ' . $appliedStudent->getUserID() . '">' . '</td> </tr>';
                                                }
                                            }?>
                                        </tbody>
                                        </form>
                                    </table>
                                </div>
                            </div>
                    <?php
                        }
                    }
                    ?>
                </div>
<?php
    }
}
?>

<?php require("template/footer.phtml") ?>
