<?php require('template/header.phtml') ?>

<div class="container">
    <div class="row">
        <div class="col-sm d-flex justify-content-center">
            <form method="post" action="registerstudent.php" class="form text-primary">
                <input type="submit" class="btn btn-secondary" name="registerstudentbutton" value="Register Student">
            </form>
        </div>
        <div class="col-sm d-flex justify-content-center">
            <form method="post" action="registeremployer.php" class="form text-primary">
                <input type="submit" class="btn btn-secondary" name="registeremployerbutton" value="Register Employer">
            </form>
        </div>
    </div>
</div>

<?php require('template/footer.phtml') ?>
