<?php require('template/header.phtml') ?>

<h2>Student</h2>
<form method="post" action="" class="form text-primary" enctype="multipart/form-data">
    <div class="form-group">
        <label for="studentEmail">Email *</label>
        <input type="email" class="form-control" placeholder="Email" name="studentEmail" required>
    </div>
    <div class="form-group">
        <label for="studentPassword">Password *</label>
        <input type="password" class="form-control" placeholder="Password" name="studentPassword" required>
    </div>
    <div class="form-group">
        <label for="studentName">Name *</label>
        <input type="text" class="form-control" placeholder="Name" name="studentName" required>
    </div>
    <div class="form-group">
        <label for="studentPhoneNumber">Phone Number *</label>
        <input type="text" class="form-control" placeholder="Phone Number" name="studentPhoneNumber" required>
    </div>
    <div class="form-group">
        <label for="studentPostalAddress">Postal Address *</label>
        <input type="text" class="form-control" placeholder="Postal Address" name="studentPostalAddress" required>
    </div>
    <div class="form-group">
        <label for="cv">CV Upload *</label>
        <input type="file" id="file" name="file" accept="application/pdf">
    </div>
    <input type="submit" class="btn btn-secondary" name="registerbutton" value="Register">
</form>
<?php
if (isset($_SESSION["registerError"]))
{
echo "<p class='error'>" . $_SESSION["registerError"] . "</p>";
unset($_SESSION["registerError"]);
}
?>

<?php require('template/footer.phtml') ?>
