        </div>
    </div>
    <!-- Footer -->
    <footer class="page-footer">

        <!-- Copyright -->
        <footer>
            <div class="footer-copyright text-center py-3">
                <p>© 2022 Copyright: HackCamp Group 18</p>
                <hr />
                <a href="https://www.facebook.com/IT.BCS" target="_blank"><img alt="facebook icon" src="/images/socials/facebook.png"></a>
                <a href="https://www.instagram.com/weare_bcs/" target="_blank"><img alt="instagram icon" src="/images/socials/instagram.png"></a>
                <a href="https://twitter.com/bcs" target="_blank"><img alt="twitter icon" src="/images/socials/twitter.png"></a>
            </div>
        </footer>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>