<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">

    <title>BCS Placements - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<div class="container-fluid">
    <div  class="row">
        <div id="title" class="col-xs-12">
            <img src="/images/BCS%20Logo.jpg" alt="BCS Logo" />
            <div class="pull-right"> <h1>Placements</h1></div>
        </div>
    </div>

    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
            <?php
            if ($_SESSION['user']->getLogStatus()) {
                echo '
            <form method="post" action="" class="form text-primary">
                <label id="status">Logged in as ' . $_SESSION["login"] .'</label>';
                if ($userTableDataSet->checkIfEmployer($_SESSION['user_id'])) {
                    echo '<label style="display: inline">(Employer)</label>';
                }
                elseif ($userTableDataSet->checkIfStudent($_SESSION['user_id']))
                {
                    echo '<label style="display: inline">(Student)</label>';
                }
                echo '
                <input id="logOut" type="submit" class="btn btn-danger" name="logoutbutton" value="Logout">
            </form>
            ';
            }

            if ($_SESSION['user']->getLogStatus()) {
                if ($userTableDataSet->checkIfEmployer($_SESSION['user_id'])) {
                    echo '<li class="pages"><a href = "index.php" > Home </a ></li>';
                    echo '<li class="pages"><a href = "createplacement.php" > Create Placement </a ></li>';
                    echo '<li class="pages"><a href = "editplacement.php" > Edit Placement </a></li>';
                    echo '<li class="pages"><a href = "editprofile.php" > Edit Profile </a ></li>';
                }
                elseif ($userTableDataSet->checkIfStudent($_SESSION['user_id']))
                {
                    echo '<li class="pages"><a href = "index.php" > Home </a ></li>';
                    echo '<li class="pages"><a href = "editprofile.php" > Edit Profile </a ></li>';
                    echo '<li class="pages"><a href = "viewacceptedplacements.php" > View Accepted Placements </a ></li>';
                }
            } else {
                echo '<li id="loginButton"><a href = "index.php" > Login</a ></li>';
                echo '<li id="regButton"><a href = "register.php" > Register</a ></li>';
            }
            ?>
        </div>
    <div id="content" class="col-xs-6 col-sm-9 col-md-10">